### ISSUE TITLE
Feature: Edit and delete mock in the dashboard

### ISSUE THREAD

**Issue by idodav** [idodav/sharkio#128]
Allow editing and delting of mocks in the dashboard. In two screens.
The mocks screen. And in the service screen.

**Comment by nakel-ola** [comment]
can I work on this issue?_

**Comment by nakel-ola** [comment]
> @nakel-ola Assigned to you

working on it

**Comment by nakel-ola** [comment]
Hey, i am adding an edit and delete icon to every mock and for the editing i am creating a new dialog to handle editing or should i manipulate the add mock dialog to support editing

**Comment by idodav** [comment]
I think it'd better to create a new dialog for editing.
