### ISSUE TITLE
Adding the GitHub icon of the repo project

### ISSUE THREAD

**Issue by OshriAsulin** [idodav/sharkio#140]
Adding the GitHub icon of the repo project to the navbar near by the login button

**Comment by OshriAsulin** [comment]
Can implement do this enhancement?

**Comment by SID262000** [comment]
Can you share any visual picture?

**Comment by idodav** [comment]
@OshriAsulin Assigned to you

**Comment by OshriAsulin** [comment]
![Screenshot 2023-07-24 172359](https://github.com/idodav/sharkio/assets/114335827/72cd1a5d-9ffe-4073-a81c-9fbdf60a41c4)

**Comment by OshriAsulin** [comment]
![עיצוב ללא שם (5)](https://github.com/idodav/sharkio/assets/114335827/55ad91b2-d0d4-4782-a066-2c7e8731378b)

**Comment by SID262000** [comment]
Is anyone working on this Issue?
@idodav @OshriAsulin

**Comment by idodav** [comment]
@OshriAsulin ?

**Comment by OshriAsulin** [comment]
yes, I am working on it

**Comment by idodav** [comment]
Thanks @OshriAsulin!
