### ISSUE TITLE
Documentation: Demo video/GIF for the readme

### ISSUE THREAD

**Issue by idodav** [idodav/sharkio#37]

**Comment by shravan20** [comment]
@idodav : Can you please assign this to me?

**Comment by shravan20** [comment]
@idodav: This has been completed, thank you so much for providing me with opportunity to contribute to the project. :)

**Comment by idodav** [comment]
> @idodav: This has been completed, thank you so much for providing me with opportunity to contribute to the project. :)

You did a great job! i was amazed thank you 😊
