### ISSUE TITLE
Feature: add service name to requests list

### ISSUE THREAD

**Issue by Oferlis** [idodav/sharkio#43]

**Comment by Oferlis** [comment]
Hey @idodav, a questions after checking a few approaches:
I could add a new type to wrap PathResponseData or edit it to contain service property or I could add it in the foreach loop in sniffer-manager. 
What do you think is the better approach?

**Comment by idodav** [comment]
I think that it is okay to edit PathResponseData to add the service name property :)

**Comment by Oferlis** [comment]
Closing this issue after merging the feature branch
