### ISSUE TITLE
Tech: linter

### ISSUE THREAD

**Issue by idodav** [idodav/sharkio#59]
Add linter with rules for react and typescript

**Comment by kabhamo** [comment]
Hi @idodav,
I found this Medium article and I think it is relevant to your demand.
Can you take a look and tell me if this is what you asking for?
https://andrebnassis.medium.com/setting-eslint-on-a-react-typescript-project-2021-1190a43ffba
If yes, I would be happy to take this issue on me :)

**Comment by idodav** [comment]
@SID262000 Thank you very much for your contribution. Also @nkotzrenko for reviewing.
Closing this issue for now!

**Comment by SID262000** [comment]
@idodav I think we should integrate these linters as part of the pre-commit hook to make sure the well-formatted code only gets pushed to the main codebase.
cc: @nkotzrenko

**Comment by idodav** [comment]
Think so as well!
