### ISSUE TITLE
Social: Write a blog post on linkedin/dev.to

### ISSUE THREAD

**Issue by idodav** [idodav/sharkio#61]
Write a blog post on linkedin/dev.to about your first contribution to sharkio.

**Comment by shravan20** [comment]
@idodav : I would love to do it, could you brief a bit about things to be included as part of the blog?

**Comment by shravan20** [comment]
@idodav: Can you please provide some details on things that you are expecting to be added as part of the blog?

**Comment by idodav** [comment]
Few ideas for posts:
1. Share a use case that Sharkio helped you develop in a daily task
2. Share your thoughts about the project
3. Write a post about the project architecture
4. Write a post about features you think you could add and how would you design them(code/ui)
6. Share about the process of how you contributed to this project. How you found the project. How you found which issue to take. How to fork and open a pull request.
7. Write a post about a feature/contribution you made in full detail.
8. Use chatGPT to develop a feature to sharkio and write about it
9. Write a post about why you are involved in opensource and why you chose to contribute specifically to this project

**Comment by Oferlis** [comment]
working on a dev.to article about sharkio and my openAPI contribution. Hope to send draft today
