### ISSUE TITLE
Feature: sharkio logo in favicon

### ISSUE THREAD

**Issue by idodav** [idodav/sharkio#62]
Add the sharkio logo the the icon in the tab.

<img width="1512" alt="Screenshot 2023-06-30 at 0 48 23" src="https://github.com/idodav/sharkio/assets/21335259/60f80a57-083e-4d19-8109-99f0e658fd57">

**Comment by kabhamo** [comment]
Hi ido,
I can help with this issue.
Assign it to me, please.
