### ISSUE TITLE
Bug: Fix curl generation

### ISSUE THREAD

**Issue by idodav** [idodav/sharkio#71]
Curl does not generate with the full path.

**Comment by kabhamo** [comment]
Hi @idodav ,
Can you add more information about the bug
I would be happy to help solve it.

**Comment by idodav** [comment]
Aswome thanks.
There is a function in the code. That receives an express HTTP request and generates a curl command for it.
You can see it here:
https://github.com/idodav/sharkio/blob/357dad7fcb34ed537d3d460dbfb91c9ff33d16d9/traffic-dashboard/src/lib/jsonSchema.ts#L123-L141
And there is a bug in this function. That it doesn't add the full path of the request to the generated curl command.

You could also see it in the dashboard in the request page:
A request was made for http://localhost:5555/user/create/dorin
And the curl generated only http://localhost:5555

<img width="1497" alt="Screenshot 2023-07-03 at 14 22 34" src="https://github.com/idodav/sharkio/assets/21335259/120ced64-ca23-4ba0-bd8e-09a539614df4">

**Comment by mnj93** [comment]
@idodav I would like to help with this one, can you assign this to me?

**Comment by idodav** [comment]
Assigned!
