### ISSUE TITLE
Feature: UI - After saving a sniffer, minimize form fields

### ISSUE THREAD

**Issue by Oferlis** [idodav/sharkio#75]
It will simplify the UI and will allow us to display other option. 
Some ideas,:
- a button to open the link in a new tab - opening the proxy is a recurring issue with first time users
- a link to the service page - https://github.com/idodav/sharkio/issues/55

**Comment by hagarfisher** [comment]
@idodav I'd like to take this issue :)

**Comment by idodav** [comment]
assigning this to you :) if you need any help feel free to ask

**Comment by idodav** [comment]
@hagarfisher Thank you very much, made us proud :)
I would love it if you could add a short video in this issue. 
Showing a demo of what you implemented.

**Comment by hagarfisher** [comment]
Thanks @idodav :) here's a short demo of the feature:
![demo](https://github.com/idodav/sharkio/assets/24765882/ffc404de-20b8-405e-af7c-dbb92edd497e)
