### ISSUE TITLE
Tech: Make thin controllers

### ISSUE THREAD

**Issue by shravan20** [idodav/sharkio#93]
**Is your feature request related to a problem? Please describe.**
Problem is currently there are redundant codes in controllers hence make them smalelr and thinner

**Comment by shravan20** [comment]
> @shravan20 Can you please give us an example about the bloated controllers? It sounds like a refactor task and I love refactoring

- Use express routers and move validation for each API and other business logic as middlewares in routes
- Create controllers to simply pass the control to services and pass control on to next middlewares that could be a success response middleware or error handler middleware.

**Comment by idodav** [comment]
@nkotzrenko Is this handled in your PR?(https://github.com/idodav/sharkio/pull/116)
Can we close this issue?

**Comment by idodav** [comment]
@nkotzrenko closing this issue. As i understood it is finished.
