### ISSUE TITLE
[Bug] Invoking API of demo server is causing it to run requests in loop

### ISSUE THREAD

**Issue by shravan20** [idodav/sharkio#97]
**Describe the bug**
The API calls for invoking the dummy API is causing the server to call itself in recursive state, causing it to crash due to minor issue the dummy server.

**To Reproduce**
- Run `npm run demo`
- Hit localhost:5432

You can check the logs

**Expected behavior**
There should not be internal call to itself within express dummy server causing this.

**Comment by Oferlis** [comment]
I had this issue when creating the config feature, adding the file to the nodemon ignore helped. Since the nodemon refreshes the build when a file it is watching changes.
Hope this helps

**Comment by shravan20** [comment]
@Oferlis: No, this is because internally we're making looped call to same server causing it to end up in recursion.
Added a fix here, this would essentially fix this.

Feel free to review this:https://github.com/idodav/sharkio/pull/98
