### ISSUE TITLE
[tech-debt] Winston Logger Setup

### ISSUE THREAD

**Issue by shravan20** [idodav/sharkio#99]
**Is your feature request related to a problem? Please describe.**
Currently, we are using console.log on screen, going ahead with moving this to production, we would need to have some sort of monitoring system integrated to this, making this available as cloud app.

As a first step towards that, we need to setup a logger application to this.

**Describe the solution you'd like**
Use winston-logger since it has a huge support and integration with multiple monitoring systems. Hence create a simple logger system either to store in .txt file or console based user input at the moment.

[winston](https://www.npmjs.com/package/winston)

**Comment by YarinLevi5** [comment]
Can I get this issue?

**Comment by idodav** [comment]
Hi @YarinLevi5 assigned this to you!

**Comment by nkotzrenko** [comment]
@idodav I can take this task under myself if need be.
@YarinLevi5 I would like to know if you have worked on it and whether you have a branch for the task that I can continue from.

**Comment by YarinLevi5** [comment]
Hi @nkotzrenko  I haven't started working on this task yet, you can take it

**Comment by nkotzrenko** [comment]
Thank you @YarinLevi5

**Comment by idodav** [comment]
Finished by @nkotzrenko. Thanks!!
